
package com.cgi.soa.masterclass.samplepay.samplebank.ws;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "BankWebService", targetNamespace = "http://ws.samplebank.masterclass.soa.cgi.com/", wsdlLocation = "file:/Users/arthurpurnama/SoaMasterclass/workspace/samplepay/src/main/resources/META-INF/BankWebService.wsdl")
public class BankWebService
    extends Service
{

    private final static URL BANKWEBSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.cgi.soa.masterclass.samplepay.samplebank.ws.BankWebService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.cgi.soa.masterclass.samplepay.samplebank.ws.BankWebService.class.getResource(".");
            url = new URL(baseUrl, "file:/Users/arthurpurnama/SoaMasterclass/workspace/samplepay/src/main/resources/META-INF/BankWebService.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'file:/Users/arthurpurnama/SoaMasterclass/workspace/samplepay/src/main/resources/META-INF/BankWebService.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        BANKWEBSERVICE_WSDL_LOCATION = url;
    }

    public BankWebService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BankWebService() {
        super(BANKWEBSERVICE_WSDL_LOCATION, new QName("http://ws.samplebank.masterclass.soa.cgi.com/", "BankWebService"));
    }

    /**
     * 
     * @return
     *     returns BankWeb
     */
    @WebEndpoint(name = "BankWebPort")
    public BankWeb getBankWebPort() {
        return super.getPort(new QName("http://ws.samplebank.masterclass.soa.cgi.com/", "BankWebPort"), BankWeb.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BankWeb
     */
    @WebEndpoint(name = "BankWebPort")
    public BankWeb getBankWebPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.samplebank.masterclass.soa.cgi.com/", "BankWebPort"), BankWeb.class, features);
    }

}
