
package com.cgi.soa.masterclass.samplepay.samplebank.ws;

import java.math.BigDecimal;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "BankWeb", targetNamespace = "http://ws.samplebank.masterclass.soa.cgi.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BankWeb {


    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "transfer", targetNamespace = "http://ws.samplebank.masterclass.soa.cgi.com/", className = "com.cgi.soa.masterclass.samplepay.samplebank.ws.Transfer")
    @ResponseWrapper(localName = "transferResponse", targetNamespace = "http://ws.samplebank.masterclass.soa.cgi.com/", className = "com.cgi.soa.masterclass.samplepay.samplebank.ws.TransferResponse")
    public void transfer(
        @WebParam(name = "arg0", targetNamespace = "")
        Integer arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        Integer arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        BigDecimal arg3);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "isBalanceCovered", targetNamespace = "http://ws.samplebank.masterclass.soa.cgi.com/", className = "com.cgi.soa.masterclass.samplepay.samplebank.ws.IsBalanceCovered")
    @ResponseWrapper(localName = "isBalanceCoveredResponse", targetNamespace = "http://ws.samplebank.masterclass.soa.cgi.com/", className = "com.cgi.soa.masterclass.samplepay.samplebank.ws.IsBalanceCoveredResponse")
    public boolean isBalanceCovered(
        @WebParam(name = "arg0", targetNamespace = "")
        Integer arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        BigDecimal arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "isAccountExist", targetNamespace = "http://ws.samplebank.masterclass.soa.cgi.com/", className = "com.cgi.soa.masterclass.samplepay.samplebank.ws.IsAccountExist")
    @ResponseWrapper(localName = "isAccountExistResponse", targetNamespace = "http://ws.samplebank.masterclass.soa.cgi.com/", className = "com.cgi.soa.masterclass.samplepay.samplebank.ws.IsAccountExistResponse")
    public boolean isAccountExist(
        @WebParam(name = "arg0", targetNamespace = "")
        Integer arg0);

}
